-- 功能表（按权限 拆分的功能，精确到按钮）
CREATE TABLE "FL_FUNCTION" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "ISEQ$$_83788"."NEXTVAL" NOT NULL,
  "NAME" NVARCHAR2(200) VISIBLE,
  "LEVEL_TYPE" NUMBER(11,0) VISIBLE,
  "PARENT_ID" NUMBER(11,0) VISIBLE,
  "DESCRIPTION" NVARCHAR2(200) VISIBLE,
  "STATUS" NUMBER(11,0) VISIBLE DEFAULT 1,
  "LINK_TYPE" NUMBER(2,0) VISIBLE DEFAULT 0,
  "ORDERBY" NUMBER(11,0) VISIBLE DEFAULT 0 NOT NULL
);
COMMENT ON COLUMN "FL_FUNCTION"."LINK_TYPE" IS '菜单类型  0普通菜单 非0跳转H5链接';
COMMENT ON COLUMN "FL_FUNCTION"."ORDERBY" IS '权限排序';