-- 角色和功能的关联表
CREATE TABLE "FL_ROLE_FUNC_MAP" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "ROLE_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "FUNC_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CREATE_ID" NUMBER(11,0) VISIBLE,
  "CTIME" NUMBER(11,0) VISIBLE,
  "CHECKED" NUMBER(11,0) VISIBLE,
  "MODIFY_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "MTIME" NUMBER(11,0) VISIBLE NOT NULL
);
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."ROLE_ID" IS '用户ID';
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."FUNC_ID" IS '功能ID';
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."CREATE_ID" IS '创建人';
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."CTIME" IS '创建时间';
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."CHECKED" IS '是否选中0否';
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."MODIFY_ID" IS '修改人';
COMMENT ON COLUMN "FL_ROLE_FUNC_MAP"."MTIME" IS '修改时间戳';


ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C0083201" PRIMARY KEY ("ID");
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C008161" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C008162" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C008163" CHECK ("FUNC_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C008164" CHECK ("MODIFY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C008165" CHECK ("MTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C0082131" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C0082141" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C0082151" CHECK ("FUNC_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C0082161" CHECK ("MODIFY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE_FUNC_MAP" ADD CONSTRAINT "SYS_C0082171" CHECK ("MTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;