-- 角色表
CREATE TABLE "FL_ROLE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CODE" NVARCHAR2(40) VISIBLE,
  "NAME" NVARCHAR2(100) VISIBLE NOT NULL,
  "REMARK" NVARCHAR2(500) VISIBLE,
  "STATUS" NUMBER(11,0) VISIBLE DEFAULT 1,
  "STATUS_TIME" NUMBER(11,0) VISIBLE,
  "INDEX" NUMBER(11,0) VISIBLE,
  "SEQUENCE" NUMBER(11,0) VISIBLE,
  "TYPE" NUMBER(11,0) VISIBLE,
  "CREATE_ID" NUMBER(11,0) VISIBLE,
  "CTIME" NUMBER(11,0) VISIBLE,
  "MODIFY_ID" NUMBER(11,0) VISIBLE,
  "MTIME" NUMBER(11,0) VISIBLE,
  "PARTNER_ID" NUMBER(11,0) VISIBLE,
  "ADMINISTRATOR_ID" NUMBER(11,0) VISIBLE,
  "ROLE_TYPE" NUMBER(1,0) VISIBLE
);
COMMENT ON COLUMN "FL_ROLE"."ID" IS '主键ID';
COMMENT ON COLUMN "FL_ROLE"."CODE" IS '编码';
COMMENT ON COLUMN "FL_ROLE"."NAME" IS '角色名称';
COMMENT ON COLUMN "FL_ROLE"."REMARK" IS '角色描述';
COMMENT ON COLUMN "FL_ROLE"."STATUS" IS '状态 0：删除，1：正常';
COMMENT ON COLUMN "FL_ROLE"."STATUS_TIME" IS '状态时间';
COMMENT ON COLUMN "FL_ROLE"."INDEX" IS '排序';
COMMENT ON COLUMN "FL_ROLE"."SEQUENCE" IS '序号';
COMMENT ON COLUMN "FL_ROLE"."TYPE" IS '1参与审批流';
COMMENT ON COLUMN "FL_ROLE"."CREATE_ID" IS '创建人';
COMMENT ON COLUMN "FL_ROLE"."CTIME" IS '创建时间';
COMMENT ON COLUMN "FL_ROLE"."MODIFY_ID" IS '最后修改人';
COMMENT ON COLUMN "FL_ROLE"."MTIME" IS '最后修改时间';
COMMENT ON COLUMN "FL_ROLE"."PARTNER_ID" IS '公司ID';
COMMENT ON COLUMN "FL_ROLE"."ADMINISTRATOR_ID" IS '子管理员配置表id';
COMMENT ON COLUMN "FL_ROLE"."ROLE_TYPE" IS '类型  1瑞福德角色  2合作商角色';
 
ALTER TABLE "FL_ROLE" ADD CONSTRAINT "SYS_C008563" PRIMARY KEY ("ID");
ALTER TABLE "FL_ROLE" ADD CONSTRAINT "SYS_C008159" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_ROLE" ADD CONSTRAINT "SYS_C008160" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;