-- 用户关联的角色信息
CREATE TABLE "FL_USER_ROLE_MAP" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "ROLE_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CREATE_ID" NUMBER(11,0) VISIBLE,
  "CTIME" NUMBER(11,0) VISIBLE,
  "PARTNER_ID" NUMBER(11,0) VISIBLE,
  "MODIFY_ID" NUMBER(11,0) VISIBLE,
  "MTIME" NUMBER(11,0) VISIBLE
)
;
COMMENT ON COLUMN "FL_USER_ROLE_MAP"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "FL_USER_ROLE_MAP"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "FL_USER_ROLE_MAP"."MODIFY_ID" IS '修改人';
COMMENT ON COLUMN "FL_USER_ROLE_MAP"."MTIME" IS '修改时间戳';


ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C0084940" PRIMARY KEY ("ID");
ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C008166" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C008167" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C008168" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C0084891" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C0084901" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "FL_USER_ROLE_MAP" ADD CONSTRAINT "SYS_C0084911" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
