
CREATE TABLE "TB_HOLIDAYS" (
  "ID" NUMBER VISIBLE DEFAULT "ISEQ$$_79550".nextval NOT NULL,
  "HOLIDAY_DATE" VARCHAR2(10 BYTE) VISIBLE NOT NULL,
  "HOLIDAY" CHAR(1 BYTE) VISIBLE NOT NULL,
  "NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "WAGE" NUMBER VISIBLE NOT NULL,
  "AFTER" CHAR(1 BYTE) VISIBLE,
  "TARGET" VARCHAR2(50 BYTE) VISIBLE,
  "STATUS" NUMBER VISIBLE DEFAULT 1
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Checks structure for table TB_HOLIDAYS
-- ----------------------------
ALTER TABLE "TB_HOLIDAYS" ADD CONSTRAINT "SYS_C009003" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TB_HOLIDAYS" ADD CONSTRAINT "SYS_C009004" CHECK ("HOLIDAY_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TB_HOLIDAYS" ADD CONSTRAINT "SYS_C009005" CHECK ("HOLIDAY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TB_HOLIDAYS" ADD CONSTRAINT "SYS_C009006" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "TB_HOLIDAYS" ADD CONSTRAINT "SYS_C009007" CHECK ("WAGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table TB_HOLIDAYS
-- ----------------------------
CREATE INDEX "TBH_STATUS"
  ON "TB_HOLIDAYS" ("STATUS" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
